-- CREATE TABLE users(
--   id SERIAL PRIMARY KEY,
--   name TEXT NOT NULL,
--   email TEXT NOT NULL UNIQUE,
--   password TEXT NOT NULL,
--   confirmPassword TEXT NOT NULL
-- )

-- CREATE TABLE urls(
--   id SERIAL PRIMARY KEY,
--   "shortUrl" TEXT NOT NULL,
--   url TEXT NOT NULL
-- )